version: 0.0
os: linux
files:
 - source: bin/
   destination: /opt/{{ APP_NAME }}/bin
 - source: etc/
   destination: /etc/systemd/system
 - source: www/
   destination: /opt/{{ APP_NAME }}/www
hooks:
  ApplicationStop:
    - location: bin/aws_alb_deregister.sh
      timeout: 420
      runas: root
    - location: bin/stop-server.sh
      timeout: 300
      runas: root
    - location: bin/clean-directory.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: bin/aws_asg_codedeploy_heartbeat.sh
      timeout: 60
      runas: root
    - location: bin/prepare-directory.sh
      timeout: 30
      runas: root
    - location: bin/configure_splunk.sh
      timeout: 300
      runas: root
  ApplicationStart: 
    - location: bin/aws_asg_codedeploy_heartbeat.sh
      timeout: 60
      runas: root
    - location: bin/start-server.sh
      timeout: 300
      runas: root
    - location: bin/aws_alb_register.sh
      timeout: 240
      runas: root
