version: 0.0
os: linux
files:
  - source: /
    destination: /opt/{{ APP_NAME }}
hooks:
  ApplicationStop:
    - location: bin/aws_alb_deregister.sh
      timeout: 420
      runas: root
    - location: bin/stop-server.sh
      timeout: 300
      runas: root
    - location: bin/remove_logs_in_splunk.sh
      timeout: 120
      runas: splunk
    - location: bin/clean-directory.sh
      timeout: 60
      runas: root
  BeforeInstall:
    # Uncomment this series of 3 sleep-300.sh scripts to validate that the
    # heartbeats are getting sent on scale-out CodeDeploys.
    #- location: bin/sleep-300.sh
    #  timeout: 360
    #  runas: root
    - location: bin/aws_asg_codedeploy_heartbeat.sh
      timeout: 60
      runas: root
    - location: bin/prepare-directory.sh
      timeout: 30
      runas: root
  AfterInstall:
    #- location: bin/sleep-300.sh
    #  timeout: 360
    #  runas: root
    - location: bin/aws_asg_codedeploy_heartbeat.sh
      timeout: 60
      runas: root
    - location: bin/get-config-files.sh
      timeout: 30
      runas: root
    - location: bin/add_logs_to_splunk.sh
      timeout: 120
      runas: splunk
  ApplicationStart: 
    - location: bin/aws_asg_codedeploy_heartbeat.sh
      timeout: 60
      runas: root
    - location: bin/start-server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: bin/validate-service.sh
      timeout: 300
      runas: root
    #- location: bin/sleep-300.sh
    #  timeout: 360
    #  runas: root
    - location: bin/aws_asg_codedeploy_heartbeat.sh
      timeout: 60
      runas: root
    - location: bin/aws_alb_register.sh
      timeout: 240
      runas: root
