---
- name: Install repositories on CentOS7
  yum: name={{ item }} update_cache=yes state=present
  with_items:
    - epel-release
    - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

- name: Enable Remi-PHP56 on CentOS 7
  ini_file:
    dest: /etc/yum.repos.d/remi.repo
    section: remi-php56
    option: enabled
    value: 1

- name: Enable Remi on CentOS 7
  ini_file:
    dest: /etc/yum.repos.d/remi.repo
    section: remi
    option: enabled
    value: 1

- name: Install php packages on CentOS 7
  yum: name={{ item }} update_cache=yes state=present
  with_items:
    - php
    - php-bcmath
    - php-cli
    - php-common
    - php-fpm
    - php-gmp
    - php-gd
    - php-intl
    - php-imap
    - php-ldap
    - php-mbstring
    - php-mcrypt
    - php-mysql
    - php-opcache
    - php-pear
    - php-pecl-apcu
    - php-pecl-memcache
    - php-pecl-mongo
    - php-pdo
    - php-pgsql
    - php-process
    - php-soap
    - php-tidy
    - php-xml
    - php-xmlrpc
    - ImageMagick

- name: Check if Composer is installed.
  stat: "path=/usr/bin/composer"
  register: composer_file

- name: Get Composer Installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not composer_file.stat.exists

- name: Run Composer Installer
  command: >
    php composer-installer.php --install-dir=/usr/bin --filename=composer
    chdir=/tmp
  when: not composer_file.stat.exists

- name: Install php conf on CentOS 7
  template:
    src: php.ini-CentOS.j2
    dest: /etc/php.ini

- name: Install www.conf on CentOS 7
  template:
    src: www.conf.j2
    dest: /etc/php-fpm.d/www.conf

- name: Configure php-fpm starting state on CentOS 7
  service:
    name: php-fpm
    state: stopped
    enabled: no

- name: set timezone to East coast
  timezone:
    name: America/New_York