---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install nginx
  apt: "name=nginx state=present"

- name: Install nginx conf
  template:
    src: nginx-Ubuntu.conf.j2
    dest: /etc/nginx.conf
  notify:
    - service nginx restart

- name: Install fastcgi conf
  template:
    src: fastcgi.conf.j2
    dest: /etc/nginx/fastcgi.conf
  notify:
    - service nginx reload

- name: Make sure that nginx is stopped and disabled at boot for Ubuntu
  service: name=nginx state=stopped enabled=no

