version: 0.0
os: linux
files:
 - source: /
   destination: /opt/{{ APP_NAME }}
   owner: root
   group: {{ APP_NAME }}
   mode: 640
 - source: etc/
   destination: /etc/systemd/system
hooks:
  ApplicationStop:
    - location: bin/aws_alb_deregister.sh
      timeout: 420
      runas: root
    - location: bin/stop-server.sh
      timeout: 300
      runas: root
    - location: bin/remove_logs_in_splunk.sh
      timeout: 120
      runas: splunk
    - location: bin/clean-directory.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: bin/aws_asg_codedeploy_heartbeat.sh
      timeout: 60
      runas: root
    - location: bin/prepare-directory.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: bin/aws_asg_codedeploy_heartbeat.sh
      timeout: 60
      runas: root
    - location: bin/download-config.sh
      timeout: 60
      runas: root
    - location: bin/implement_new_relic_apm.sh
      timeout: 120
      runas: root
    - location: bin/add_logs_to_splunk.sh
      timeout: 120
      runas: splunk
    - location: bin/prepare-logging.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: bin/aws_asg_codedeploy_heartbeat.sh
      timeout: 60
      runas: root
    - location: bin/start-server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: bin/aws_asg_codedeploy_heartbeat.sh
      timeout: 60
      runas: root
    - location: bin/validate-service.sh
      timeout: 60
      runas: root
    - location: bin/aws_alb_register.sh
      timeout: 240
      runas: root
